FROM node:24 AS build

WORKDIR /app
COPY . .
RUN npm ci
RUN npm run compile && npm run build

FROM node:24

WORKDIR /app
COPY --from=build /app/ ./

ENV NODE_ENV=production
ENV DATABASE_CLIENT=sqlite
ENV DATA_DIR=/data

EXPOSE 3000 3001

CMD ["npm", "run", "start-docker"]
